apiVersion: apps/v1
kind: Deployment
metadata:
  name: twoge-kube-deployment
  namespace: matt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: twoge-kube
  template:
    metadata:
      labels:
        app: twoge-kube
    spec:
      containers:
      - name: twoge-kube
        image: matthewjames4187/twoge:latest
        ports:
          - containerPort: 8080
        readinessProbe:
            httpGet:
              path: /
              port: 8080
            successThreshold: 3
            periodSeconds: 5
        resources:
          requests:
            cpu: "50m"
            memory: "50Mi"
          limits:
            cpu: "100m"
            memory: "100Mi"
        env:
          - name: PG_USER
            valueFrom:
              configMapKeyRef:
                name: twoge-configmap
                key: PG_USER
          - name: PG_PASSWORD
            valueFrom:
              secretKeyRef:
                name: database-secrets
                key: PG_PASSWORD
          - name: PG_HOST
            valueFrom:
              configMapKeyRef:
                name: twoge-configmap
                key: PG_HOST
          - name: PG_PORT
            valueFrom:
              configMapKeyRef:
                name: twoge-configmap
                key: PG_PORT
          - name: PG_DATABASE
            valueFrom:
              configMapKeyRef:
                name: twoge-configmap
                key: PG_DATABASE
