# Java App Service
apiVersion: v1
kind: Service
metadata:
  name: twoge
  namespace: matt
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30090
  selector:
    app: twoge-kube