apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  labels:
    build: twoge
spec:
  capacity:
    storage: 4Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  claimRef:
    namespace: matt
    name: postgres-pvc
  hostPath:
    path: /mnt/data/postgres