#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: postgres-pvc
#spec:
#  accessModes:
#    - ReadWriteOnce
#  volumeMode: Filesystem
#  resources:
#    requests:
#      storage: 1Gi
#  selector:
#    matchLabels:
#      build: twoge

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: matt
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

