apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: slow-storage
  namespace: matt
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true