name: Twoge CICD
on:
  push:
    branches:
      - eks-cluster
env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  AWS_REGION: 'us-east-1'
  K8S_NAMESPACE: 'eks-cicd'
  EKS_CLUSTER_NAME: 'cpclass-eks-cluster'
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
        with:
          ref: eks-cluster
      - name: set up docker buildx
        uses: docker/setup-buildx-action@v1
      - name: login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}
      - name: build and push docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_USERNAME }}/twoge:latest
  eks_deploy:
    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
        with:
          ref: eks-cluster
      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: configure kubectl
        uses: azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}
      - name: deploy to eks
        run: |
          kubectl apply -f k8s-postgres-dep.yml/ -n matt
      - name: Delay for 15
        run: sleep 15
      - name: Deploy EKS
        run: |
          kubectl apply -f k8s-app-dep.yml/ -n matt
